### ISSUE TITLE
Implement WITH - AS for the model viewer

### ISSUE THREAD

**Issue by lmichel** [lmichel/pyvo#19]
Implement both `__enter__` and `__exit__` methods to make with `WITH ....AS`

```python
with ModelViewer("MyVoTable.xml") as model_viewer:
   do something
```
This prevents issues with missing `close`statements. 

Some explanation can be found [here](https://stackoverflow.com/questions/3774328/implementing-use-of-with-object-as-f-in-custom-class-in-python)

**Comment by somilia** [comment]
Done
