### ISSUE TITLE
Write a release note

### ISSUE THREAD

**Issue by lmichel** [lmichel/pyvo#9]
And give its location here for the review

**Comment by somilia** [comment]
# Processing VO Model Annotations

## Introduction

Model Instances in VOTables ([MIVOT](https://ivoa.net/documents/MIVOT/20230620/REC-mivot-1.0.pdf)) defines a syntax for mapping VOTable data to any model serialized in VO-DML (Virtual Observatory Data Modeling Language).

This annotation schema acts as a bridge between  data and  models. It associates both column/parameter metadata and VOTable data with data model elements (such as classes, attributes, types, etc.). It also complements VOTable data or metadata that may be missing from the table, e.g., coordinate system descriptions or curation tracing.

The data model elements are organized in an independent annotation block complying with the MIVOT XML schema, which is added as an extra resource above the TABLE element. The MIVOT syntax allows a data structure to be described as a hierarchy of classes. It can also represent relationships and compositions between them. Furthermore, it can construct data model objects by aggregating instances from different tables of the VOTable.

## Usage

The end user API allows  to obtain a model view on the last read data row, this usage corresponds to the layer 3 described below.

```
activate_features('MIVOT')
data_path = os.path.dirname(os.path.realpath(__file__))
votable = os.path.join(data_path, "tests/data/simple-annotation-votable.xml")

m_viewer = ModelViewer(votable)
row_view = m_viewer.get_next_row_view()

print(row_view.longitude.value)
```
You can access each value of the object of the model. e.g.:
`>>> print(row_view.Coordinate_coosys.PhysicalCoordSys_frame.spaceRefFrame.value)`
`>>> ICRS`

The model view is a dynamically generated Python object whose field names are derived from the `dmroles` of the MIVOT elements. There is no checking against the model structure at this level.

In this pull request, JOIN and dynamic references are not implemented. We keep focused on simpler patterns: The MIVOT block maps one mapped data table with the coordinate systems in the GLOBALS

## PyVO Implementation

The implementation relies on the Astropy's write and read annotation modules (PR#15390), which allows to get and set Mivot blocks from/into VOTables. We use this new Astropy feature, MIVOT, to retrieve the MIVOT block.
This implementation is built in 3 layers, denoting the abstraction level in relation to the XML block.
### Layer 0: `ModelViewer`
Provide the MIVOT block as it is in the VOTable: No references are resolved. The Mivot block is provided as an lxml tree.
### Layer 1: `ModelViewerLayer1`
Provide access to an xml tree whose structure matches the model view of the current row. The internal references have been resolved. The attribute values have been set with the actual data values. This XML element is intended to be used as a basis for building any objects. The layer 1 output can be browsed using XPATH queries.
### Layer 2: `ModelViewerLayer2`
Just a few methods to make the browsing of the layer 1 output easier. The layer 2 API allows users to retrieve MIVOT elements by their `@dmrole` or `@dmtype`. At this level, the MIVOT block must still be handled as an lxml element. 
This module is not completely implemented.
### Layer 3: `ModelViewerLayer3`
ModelViewerLayer3 generates, from the layer 1 output, a nested dictionary representing the entire XML INSTANCE with its hierarchy.
From this dictionary, we build a `~pyvo.mivot.viewer.mivot_class.MivotClass` object, which is a dictionary containing only the essential information used to process data.
`MivotClass` basically stores all XML objects in its attribute dictionary `__dict__`.
### Layer stacking
The more layers we have , the more elements are hidden:
- Hide column parsing: column identifiers in row view are replaced by model object.
(e.g. `get_attribute_by_role(coords:LonLatPoint.longitude)`)
- Hide MIVOT identifiers: MIVOT XML identifiers (INSTANCE, COLLECTION, ATTRIBUTE) are replaced by model elements.
(e.g. `EpochPosition.longitude.value`)
- Hide model elements: model elements are replaced by library instances.
(e.g. `EpochPosition.get_sky_coord()`)
| Layer | Column parsing | MIVOT Identifiers | Models elements |
| ------------ | ------------ | ------------ | ------------ |
| Layer 1 & 2 | Hidden | Showed | Showed |
| Layer 3 | Hidden | Hidden | Showed |
| Layer 4 | Hidden | Hidden | Hidden |

### Mivot package content:
#### Utils sub-package
This package contains modules that make it easier to handle XML elements and dictionaries, as well as the logger setup.
#### Seeker sub-package
- `AnnotationSeeker` provides a set of tools for extracting mapping sub-blocks to retrieve XML elements.
- `RessourceSeeker` provides a set of getters for tables.
- `TableIterator` is a simple wrapper that iterates over table rows.
#### Feature sub-package
This package contains features such as `StaticReferenceResolver` which is used to resolve references (replace REFERENCE elements with the referenced objects set with the roles of the REFERENCEs). Future features to be added to this sub-package include `DynamicReference` and `Join`.
#### Exception sub-package
This package contains exception classes related to MIVOT.
#### Viewer sub-package
This package contains all the layers of ModelViewer described above, as well as the `MivotClass` file.


### Test strategy:
The test module contains one pytest file per Python module, and the datasets used for the tests are located in the 'test/data' directory. The tests check for values, intermediate objects (dictionaries), errors, and thrown exceptions.
